version: '3.8'

services:
  minio:
    image: minio/minio:RELEASE.2025-02-18T16-25-55Z
    restart: always
    volumes:
      - ./data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_ACCESS_KEY=aminioadmin
      - MINIO_SECRET_KEY=sminioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"

  minio-setup:
    depends_on:
      - minio
    image: minio/mc:RELEASE.2025-02-15T10-36-16Z
    container_name: mc
    environment:
      - MINIO_ACCESS_KEY=aminioadmin
      - MINIO_SECRET_KEY=sminioadmin
    volumes:
      - ./data:/data
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add minio http://minio:9000 minio minio123) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc rm -r --force minio/datalake;
      /usr/bin/mc mb minio/datalake;
      /usr/bin/mc policy set public minio/datalake;
      exit 0;
      "   

  trino:
    image: trinodb/trino:476
    container_name: trino
    ports:
      - "8080:8080"
    volumes:
      - ./trino/etc:/etc/trino

  postgres-metastore:
    image: postgres:13
    container_name: postgres-metastore
    environment:
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
      POSTGRES_DB: metastore
    ports:
      - "5433:5432"

  postgres-dwh:
    image: postgres:13
    container_name: postgres-dwh
    environment:
      POSTGRES_USER: dwh
      POSTGRES_PASSWORD: dwh
      POSTGRES_DB: dwh
    ports:
      - "5434:5432"

  hive-metastore:
    image: bitsondatadev/hive-metastore:latest
    container_name: hive-metastore
    environment:
      METASTORE_DB_HOSTNAME: postgres-metastore
      METASTORE_DB_PORT: 5432
      METASTORE_DB_DBNAME: metastore
      METASTORE_DB_USER: hive
      METASTORE_DB_PASS: hive
    ports:
      - "9083:9083"
    depends_on:
      - postgres-metastore
    volumes:
      - ./hive/conf/metastore-site.xml:/opt/apache-hive-metastore-3.0.0-bin/conf/metastore-site.xml:ro